@url_dev=http://localhost:3052/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop 1",
    "email": "example@example.com",
    "password": "abcdxyznmasad"
}